# Generated by Django 2.2.17 on 2021-05-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210505_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
