# Generated by Django 3.2 on 2021-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210507_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name_project',
            field=models.TextField(null=True),
        ),
    ]
