# Generated by Django 3.2 on 2021-05-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_project_name_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
    ]
