# Generated by Django 3.2 on 2021-05-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='who',
            field=models.TextField(blank=True, null=True),
        ),
    ]
